auth_type: basic
board:
    id: 124
    name: SQUAL Board
    type: scrum
epic:
    name: customfield_10010
    link: customfield_10013
installation: Cloud
issue:
    fields:
        custom:
            - name: Customer Information
              key: customfield_10074
              schema:
                datatype: option
            - name: Prospect Name
              key: customfield_10075
              schema:
                datatype: string
            - name: Target start
              key: customfield_10076
              schema:
                datatype: date
            - name: Customer User ID
              key: customfield_10230
              schema:
                datatype: string
            - name: Target end
              key: customfield_10077
              schema:
                datatype: date
            - name: Submitted forms
              key: customfield_10110
              schema:
                datatype: number
            - name: Mission/Screener/Panel ID
              key: customfield_10231
              schema:
                datatype: string
            - name: Locked forms
              key: customfield_10111
              schema:
                datatype: number
            - name: Time to triage normal change
              key: customfield_10199
              schema:
                datatype: sd-servicelevelagreement
            - name: Entry/Submission/Interview ID
              key: customfield_10232
              schema:
                datatype: string
            - name: Start date
              key: customfield_10079
              schema:
                datatype: date
            - name: Total forms
              key: customfield_10112
              schema:
                datatype: number
            - name: User ID
              key: customfield_10233
              schema:
                datatype: string
            - name: Browser
              key: customfield_10234
              schema:
                datatype: option
            - name: Affected version
              key: customfield_10235
              schema:
                datatype: string
            - name: Pending reason
              key: customfield_10104
              schema:
                datatype: option
            - name: Prospect name
              key: customfield_10225
              schema:
                datatype: string
            - name: User documentation shared
              key: customfield_10105
              schema:
                datatype: option
            - name: Subscriber User ID
              key: customfield_10226
              schema:
                datatype: number
            - name: SSO request type
              key: customfield_10106
              schema:
                datatype: option
            - name: Subscriber User ID
              key: customfield_10227
              schema:
                datatype: string
            - name: Account ID & name
              key: customfield_10107
              schema:
                datatype: string
            - name: Affected product
              key: customfield_10228
              schema:
                datatype: option
            - name: Customer Identity Provider
              key: customfield_10108
              schema:
                datatype: string
            - name: Affected product
              key: customfield_10229
              schema:
                datatype: option
            - name: Open forms
              key: customfield_10109
              schema:
                datatype: number
            - name: asdas
              key: customfield_10180
              schema:
                datatype: string
            - name: Affected Product Area
              key: customfield_10060
              schema:
                datatype: option
            - name: User documentation shared
              key: customfield_10181
              schema:
                datatype: option
            - name: Affected Version
              key: customfield_10061
              schema:
                datatype: number
            - name: SSO request type
              key: customfield_10182
              schema:
                datatype: option
            - name: Severity
              key: customfield_10062
              schema:
                datatype: option
            - name: Account ID & name
              key: customfield_10183
              schema:
                datatype: string
            - name: Prioritization
              key: customfield_10063
              schema:
                datatype: option
            - name: Customer Identity Provider
              key: customfield_10184
              schema:
                datatype: string
            - name: Feature Request Time to First Response
              key: customfield_10065
              schema:
                datatype: sd-servicelevelagreement
            - name: Age
              key: customfield_10066
              schema:
                datatype: any
            - name: Visibility
              key: customfield_10067
              schema:
                datatype: option
            - name: T-shirt size
              key: customfield_10100
              schema:
                datatype: string
            - name: Product categorization
              key: customfield_10101
              schema:
                datatype: option-with-child
            - name: Operational categorization
              key: customfield_10102
              schema:
                datatype: option-with-child
            - name: Approvers
              key: customfield_10223
              schema:
                datatype: array
                items: user
            - name: Urgency
              key: customfield_10103
              schema:
                datatype: option
            - name: Customer information
              key: customfield_10224
              schema:
                datatype: option
            - name: Request language
              key: customfield_10050
              schema:
                datatype: sd-request-lang
            - name: Affected Product
              key: customfield_10051
              schema:
                datatype: option
            - name: Customer User ID
              key: customfield_10052
              schema:
                datatype: string
            - name: Mission/Screener/Panel ID
              key: customfield_10053
              schema:
                datatype: number
            - name: Vulnerability
              key: customfield_10295
              schema:
                datatype: any
            - name: Entry/Submission/Interview ID
              key: customfield_10054
              schema:
                datatype: number
            - name: User ID
              key: customfield_10055
              schema:
                datatype: number
            - name: Sentiment
              key: customfield_10297
              schema:
                datatype: array
                items: sd-sentiment
            - name: Browser
              key: customfield_10056
              schema:
                datatype: array
                items: option
            - name: Phone OS
              key: customfield_10057
              schema:
                datatype: array
                items: option
            - name: Phone Model
              key: customfield_10058
              schema:
                datatype: string
            - name: Time to first response
              key: customfield_10049
              schema:
                datatype: sd-servicelevelagreement
            - name: Story Points
              key: customfield_10043
              schema:
                datatype: number
            - name: Approvals
              key: customfield_10045
              schema:
                datatype: sd-approvals
            - name: Satisfaction
              key: customfield_10046
              schema:
                datatype: sd-feedback
            - name: Satisfaction date
              key: customfield_10047
              schema:
                datatype: datetime
            - name: T Shirt Size Estimate
              key: customfield_10201
              schema:
                datatype: option
            - name: Time to resolution
              key: customfield_10048
              schema:
                datatype: sd-servicelevelagreement
            - name: Developer
              key: customfield_10032
              schema:
                datatype: user
            - name: Story point actual
              key: customfield_10033
              schema:
                datatype: number
            - name: Issue color
              key: customfield_10027
              schema:
                datatype: string
            - name: Time to done
              key: customfield_10148
              schema:
                datatype: sd-servicelevelagreement
            - name: Goals
              key: customfield_10304
              schema:
                datatype: array
                items: Goals
            - name: Number of comments
              key: customfield_10305
              schema:
                datatype: number
            - name: Project overview status
              key: customfield_10140
              schema:
                datatype: string
            - name: Rank
              key: customfield_10020
              schema:
                datatype: any
            - name: Request participants
              key: customfield_10021
              schema:
                datatype: array
                items: user
            - name: Request Type
              key: customfield_10022
              schema:
                datatype: sd-customerrequesttype
            - name: Flagged
              key: customfield_10024
              schema:
                datatype: array
                items: option
            - name: Parent Link
              key: customfield_10016
              schema:
                datatype: any
            - name: '[CHART] Date of First Response'
              key: customfield_10017
              schema:
                datatype: datetime
            - name: '[CHART] Time in Status'
              key: customfield_10018
              schema:
                datatype: any
            - name: Project overview key
              key: customfield_10139
              schema:
                datatype: string
            - name: Sprint
              key: customfield_10019
              schema:
                datatype: array
                items: json
            - name: Date of hire
              key: customfield_10090
              schema:
                datatype: date
            - name: Location
              key: customfield_10091
              schema:
                datatype: string
            - name: Responders
              key: customfield_10093
              schema:
                datatype: array
                items: string
            - name: Cycle Time
              key: customfield_10095
              schema:
                datatype: number
            - name: Moved to In Progress
              key: customfield_10096
              schema:
                datatype: datetime
            - name: Work category
              key: customfield_10097
              schema:
                datatype: string
            - name: Time to review normal change
              key: customfield_10130
              schema:
                datatype: sd-servicelevelagreement
            - name: Approver groups
              key: customfield_10098
              schema:
                datatype: array
                items: group
            - name: Root cause
              key: customfield_10131
              schema:
                datatype: string
            - name: Epic Status
              key: customfield_10011
              schema:
                datatype: option
            - name: Done Requirements
              key: customfield_10099
              schema:
                datatype: string
            - name: Workaround
              key: customfield_10132
              schema:
                datatype: string
            - name: Epic Color
              key: customfield_10012
              schema:
                datatype: string
            - name: Start date
              key: customfield_10014
              schema:
                datatype: date
            - name: Story point estimate
              key: customfield_10015
              schema:
                datatype: number
            - name: Change type
              key: customfield_10005
              schema:
                datatype: option
            - name: Test plan
              key: customfield_10126
              schema:
                datatype: string
            - name: Change risk
              key: customfield_10006
              schema:
                datatype: option
            - name: Source
              key: customfield_10127
              schema:
                datatype: option
            - name: Change reason
              key: customfield_10007
              schema:
                datatype: option
            - name: Investigation reason
              key: customfield_10128
              schema:
                datatype: option
            - name: Change start date
              key: customfield_10008
              schema:
                datatype: datetime
            - name: Time to close after resolution
              key: customfield_10129
              schema:
                datatype: sd-servicelevelagreement
            - name: Change completion date
              key: customfield_10009
              schema:
                datatype: datetime
            - name: Employee location
              key: customfield_10080
              schema:
                datatype: string
            - name: Employment type
              key: customfield_10081
              schema:
                datatype: option
            - name: Job title
              key: customfield_10082
              schema:
                datatype: string
            - name: Manager
              key: customfield_10083
              schema:
                datatype: array
                items: user
            - name: Last working day
              key: customfield_10084
              schema:
                datatype: date
            - name: Resignation date
              key: customfield_10085
              schema:
                datatype: date
            - name: Affected services
              key: customfield_10086
              schema:
                datatype: array
                items: service-entity-field
            - name: Hiring manager
              key: customfield_10087
              schema:
                datatype: string
            - name: Major incident
              key: customfield_10120
              schema:
                datatype: string
            - name: Development
              key: customfield_10000
              schema:
                datatype: any
            - name: Job role
              key: customfield_10088
              schema:
                datatype: string
            - name: Severity
              key: customfield_10121
              schema:
                datatype: option
            - name: Team
              key: customfield_10001
              schema:
                datatype: team
            - name: Department
              key: customfield_10089
              schema:
                datatype: string
            - name: Planned start
              key: customfield_10122
              schema:
                datatype: datetime
            - name: Organizations
              key: customfield_10002
              schema:
                datatype: array
                items: sd-customerorganization
            - name: Planned end
              key: customfield_10123
              schema:
                datatype: datetime
            - name: Approvers
              key: customfield_10003
              schema:
                datatype: array
                items: user
            - name: Implementation plan
              key: customfield_10124
              schema:
                datatype: string
            - name: Impact
              key: customfield_10004
              schema:
                datatype: option
            - name: Backout plan
              key: customfield_10125
              schema:
                datatype: string
            - name: Category
              key: customfield_10115
              schema:
                datatype: option
            - name: Phone model
              key: customfield_10236
              schema:
                datatype: string
            - name: Design Link
              key: customfield_10237
              schema:
                datatype: string
            - name: Builder or viewer?
              key: customfield_10116
              schema:
                datatype: option
            - name: P1 Beta?
              key: customfield_10117
              schema:
                datatype: option
            - name: Design
              key: customfield_10239
              schema:
                datatype: array
                items: design.field.name
            - name: PM
              key: customfield_10118
              schema:
                datatype: array
                items: user
            - name: Affected hardware
              key: customfield_10119
              schema:
                datatype: string
    types:
        - id: "10000"
          name: Epic
          handle: Epic
          subtask: false
        - id: "10001"
          name: Story
          handle: Story
          subtask: false
        - id: "10010"
          name: Bug
          handle: Bug
          subtask: false
        - id: "10009"
          name: Sub-task
          handle: Sub-task
          subtask: true
        - id: "10029"
          name: Spike
          handle: Spike
          subtask: false
login: shelton.tolbert@dscout.com
project:
    key: SQUAL
    type: classic
server: https://dscout.atlassian.net
timezone: America/Chicago
